export default {
  SET_TOKEN: 'SET_TOKEN',
  SET_ALERT_STATE: 'SET_ALERT_STATE',
  SET_ALERT_MESSAGE: 'SET_ALERT_MESSAGE',
  SET_ALERT_COLOR: 'SET_ALERT_COLOR',
  SET_ALERT_TIMEOUT: 'SET_ALERT_TIMEOUT',

  SET_QUESTIONS: 'SET_QUESTIONS',
  ADD_QUESTION: 'ADD_QUESTION',
  REMOVE_QUESTION: 'REMOVE_QUESTION',
  DUPLICATE_QUESTION: 'DUPLICATE_QUESTION',
};
