export default {
  SET_TOKEN: 'SET_TOKEN',
  SET_ALERT_STATE: 'SET_ALERT_STATE',
  SET_ALERT_MESSAGE: 'SET_ALERT_MESSAGE',
  SET_ALERT_COLOR: 'SET_ALERT_COLOR',
  SET_ALERT_TIMEOUT: 'SET_ALERT_TIMEOUT',
  SET_USER: 'SET_USER',
};
